# ذاكرة الـ JVM — مهمة جداً لنجاح البيلد على GitHub Actions
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8

# تسريع البيلد
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official
kotlin.incremental=true

# إخفاء تحذيرات غير مهمة
android.defaults.buildfeatures.buildconfig=false
android.suppressUnsupportedCompileSdk=35
